class PIDController:
    """
    PIDController class can be used give PID controls to one input of a given system.
    Methods
    -------
    __init__(self, kp, ki, kd, ts)
        Constructor the the PIDController class.
    control(self, recorded_value, set_point=0)
        Outputs the PID controlled input for the system, based 1 recorded value, and set-point
    Attributes
    ----------
    __kp: float
        P constant
    __ki: float
        I constant
    __kd: float
        D constant
    __ts: float
        sampling time
    __err_previous = None : float
        previous value of error recorded
    __error_sum = 0 : float
        sum of all the errors
    """

    def __init__(self, kp, ki, kd, ts):
        """
        Constructor the the PIDController class.
        :param kp: float representing P constant
        :param ki: float representing I constant
        :param kd: float representing D constant
        :param ts: float representing the sampling time
        """
        self.__kp = kp  # Controller's P constant
        self.__kd = kd / ts  # Controller's D constant
        self.__ki = ki * ts  # Controller's I constant
        self.__ts = ts  # Controller's sampling time
        self.__err_previous = None  # Controller's previous error (there is no error before t = 0s)
        self.__error_sum = 0  # Controller's cumulative error

    def control(self, recorded_value, set_point=0.0):
        """
        Outputs the PID controlled input for the system, based 1 recorded value, and set-point
        :param recorded_value: float representing the recorded value
        :param set_point: float representing the set-point of the system
        :return: float representing the output generated by the controller
        """
        error = set_point - recorded_value  # Calculating the current error
        # print(error)

        output = self.__kp * error  # P Component
        output += self.__ki * (self.__error_sum + error)  # I Component

        if self.__err_previous is not None:
            output += self.__kd * (error - self.__err_previous)  # D Component

        self.__error_sum += error  # Cumulative Error
        self.__err_previous = error  # Previous Error

        return output
